Chunksize in bytes instead of samples
RedisTimeSeries/RedisTimeSeries pull request #502
Opened 2020-08-22 22:15 UTC by ashtul

2020-08-24 13:12 UTC, K-Jo commented
removed api breaking.  This feature was never documented

2020-08-24 14:09 UTC, filipecosta90 requested changes

2020-08-25 21:42 UTC, ashtul commented on src/consts.h
> +#define Chunk_SIZE_BYTES_SECS           4000LL   // fills one page 4096
The struct takes 80 bytes so this means they might allocated on the same page, but then, it probably won't and we expect the have new chunks...
Good point

2020-08-25 22:40 UTC, filipecosta90 approved these changes

2020-08-26 04:30 UTC, merged