Adds a quickstart page to the docs
RedisTimeSeries/RedisTimeSeries pull request #832
Opened 2021-08-17 12:36 UTC by elena-kolevska

2021-08-17 12:36 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RedisTimeSeries/RedisTimeSeries?pullRequest=832) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RedisTimeSeries/RedisTimeSeries?pullRequest=832) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RedisTimeSeries/RedisTimeSeries?pullRequest=832) it.</sub>

2021-08-18 20:12 UTC, K-Jo commented
Thank you @elena-kolevska!

2021-08-18 20:15 UTC, K-Jo requested changes
Can we cross-link the commands back to the index full explanation?
The new quickstart no longer contains how to connect with redis-cli.  Though obvious for us, this is not necessarily obvious to the new user.

2021-08-19 10:37 UTC, elena-kolevska commented
@K-Jo  Done. I shortened the redis-cli example to a single command, because we have more detailed sections for the rest of the commands.

2021-09-08 18:26 UTC, K-Jo approved these changes

2021-09-13 16:24 UTC, merged